/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tNmwcnFtkYm
 */
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import VideoPlayer from './shared/VideoPlayer'

export function SampleLandingPageV0() {
  return (
    <div className='flex flex-col min-h-screen'>
      <header className='sticky top-0 z-40 bg-white bg-opacity-10 shadow'>
        <div className='w-full mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'>
          <div className='flex items-center justify-between h-14'>
            <div className='flex items-center space-x-4'>
              <a className='text-lg font-bold' href='#'>
                Acme Inc
              </a>
              <div className='hidden md:flex w-96'>
                <form className='flex w-full rounded-lg border'>
                  <Button
                    className='h-8 rounded-l-none'
                    size='sm'
                    variant='default'>
                    <SearchIcon className='w-4 h-4' />
                    <span className='sr-only'>Submit search</span>
                  </Button>
                  <Input
                    className='w-full h-8 sm:text-sm md:text-base'
                    placeholder='Search'
                    type='search'
                  />
                </form>
              </div>
            </div>
            <nav className='flex items-center space-x-4'>
              <a className='font-medium text-sm sm:text-base' href='#'>
                Docs
              </a>
              <a className='font-medium text-sm sm:text-base' href='#'>
                Pricing
              </a>
              <a className='font-medium text-sm sm:text-base' href='#'>
                Contact
              </a>
              <Button size='sm' variant='outline'>
                Log in
              </Button>
            </nav>
          </div>
        </div>
      </header>
      <main className='flex-1 flex flex-col gap-4'>
        <VideoPlayer />
      </main>
      <footer className='sticky bottom-0 z-40 bg-white bg-opacity-10 shadow flex shrink-0 items-center px-4 md:px-6'>
        <div className='mx-auto max-w-7xl grid gap-4 py-4 md:grid-cols-2 md:py-4 lg:gap-2'>
          <div className='flex items-center space-x-2'>
            <MailIcon className='h-6 w-6' />
            <div className='text-sm font-medium'>
              Subscribe to our newsletter for the latest updates
            </div>
          </div>
          <form className='flex items-center space-x-4 md:justify-end'>
            <Input
              className='max-w-xs form:rounded-lg'
              placeholder='Enter your email'
              type='email'
            />
            <Button type='submit'>Subscribe</Button>
          </form>
        </div>
      </footer>
    </div>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <circle cx='11' cy='11' r='8' />
      <path d='m21 21-4.3-4.3' />
    </svg>
  )
}

function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <path d='M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z' />
      <path d='m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z' />
      <path d='M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0' />
      <path d='M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5' />
    </svg>
  )
}

function PaletteIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <circle cx='13.5' cy='6.5' r='.5' />
      <circle cx='17.5' cy='10.5' r='.5' />
      <circle cx='8.5' cy='7.5' r='.5' />
      <circle cx='6.5' cy='12.5' r='.5' />
      <path d='M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z' />
    </svg>
  )
}

function BoldIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <path d='M14 12a4 4 0 0 0 0-8H6v8' />
      <path d='M15 20a4 4 0 0 0 0-8H6v8Z' />
    </svg>
  )
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <rect width='20' height='16' x='2' y='4' rx='2' />
      <path d='m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7' />
    </svg>
  )
}
